language: java

script: 
  - cd dominio 
  - mvn clean install

after_success:
  - cd dominio
  - mvn clean test org.jacoco:jacoco-maven-plugin:report org.eluder.coveralls:coveralls-maven-plugin:report
