language: java

install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - cd dominio 
  - mvn test jacoco:report
after_success:
  - cd dominio 
  - mvn coveralls:report
